wandb_version: 1

batch_size:
  value: 2048
dropout:
  value: 0.4031523578257925
epochs:
  value: 150
hidden_dims:
  value:
  - 512
  - 256
  - 128
  - 64
lr:
  value: 0.0021774224176103604
patience:
  value: 80
weight_decay:
  value: 0.0004155503446324738
