wandb_version: 1

batch_size:
  value: 1028
dropout:
  value: 0.21235456149823084
epochs:
  value: 150
hidden_dims:
  value:
  - 512
  - 256
  - 128
  - 64
lr:
  value: 0.00016626652734046688
patience:
  value: 80
weight_decay:
  value: 0.0005440397452404962
