_wandb:
    value:
        cli_version: 0.23.0
        e:
            yztvln93vdzztaazt0b9xtzlmn6mxear:
                codePath: c:\Users\Jaime\Documents\GitHub\DS-HPE\training.ipynb
                codePathLocal: training.ipynb
                cpu_count: 16
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "988897341440"
                        used: "416329084928"
                email: 100451397@alumnos.uc3m.es
                executable: c:\Users\Jaime\miniconda3\python.exe
                gpu: NVIDIA GeForce RTX 5060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 3328
                      memoryTotal: "8546942976"
                      name: NVIDIA GeForce RTX 5060 Laptop GPU
                      uuid: GPU-bf1784b3-28c2-3ce3-6d35-c13096256abd
                host: DESKTOP-9G0MLGE
                memory:
                    total: "33713815552"
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\Jaime\Documents\GitHub\DS-HPE\training.ipynb
                python: CPython 3.13.9
                root: c:\Users\Jaime\Documents\GitHub\DS-HPE
                startedAt: "2025-12-16T11:05:01.537742Z"
                writerId: yztvln93vdzztaazt0b9xtzlmn6mxear
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 5
                - 6
                - 8
                - 53
            "2":
                - 1
                - 5
                - 6
                - 8
                - 53
            "3":
                - 2
                - 13
                - 14
                - 16
                - 62
            "4": 3.13.9
            "5": 0.23.0
            "8":
                - 1
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 1028
device:
    value: cuda
dropout:
    value: 0.39518388371993096
epochs:
    value: 150
hidden_dims:
    value:
        - 512
        - 256
        - 128
        - 64
        - 32
lr:
    value: 0.0025128187493725584
patience:
    value: 100
weight_decay:
    value: 0
