wandb_version: 1

batch_size:
  value: 2048
dropout:
  value: 0.21992200275637563
epochs:
  value: 150
hidden_dims:
  value:
  - 1024
  - 512
  - 256
lr:
  value: 0.008146483649146021
patience:
  value: 80
weight_decay:
  value: 8.185315014518157e-05
