wandb_version: 1

batch_size:
  value: 2048
dropout:
  value: 0.23149860195314445
epochs:
  value: 150
hidden_dims:
  value:
  - 512
  - 256
  - 128
  - 64
lr:
  value: 0.00928548982011679
patience:
  value: 80
weight_decay:
  value: 3.056974947021553e-05
