wandb_version: 1

batch_size:
  value: 2048
dropout:
  value: 0.23676812706354736
epochs:
  value: 150
hidden_dims:
  value:
  - 1024
  - 512
  - 256
lr:
  value: 0.008981843110054217
patience:
  value: 80
weight_decay:
  value: 4.46389130670416e-05
