wandb_version: 1

batch_size:
  value: 512
dropout:
  value: 0.1431626736887829
epochs:
  value: 150
hidden_dims:
  value:
  - 256
  - 128
  - 64
lr:
  value: 0.0025875010605549147
patience:
  value: 80
weight_decay:
  value: 2.12093347472324e-05
