wandb_version: 1

batch_size:
  value: 2048
dropout:
  value: 0.195605887626735
epochs:
  value: 150
hidden_dims:
  value:
  - 256
  - 128
  - 64
lr:
  value: 0.00019224932680976775
patience:
  value: 100
weight_decay:
  value: 0.0001
