_wandb:
    value:
        cli_version: 0.23.0
        e:
            rvv8zu4mff2nxbcukounvl6dnrtjjrvq:
                codePath: c:\Users\Jaime\Documents\GitHub\DS-HPE\training.ipynb
                codePathLocal: training.ipynb
                cpu_count: 16
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "988897341440"
                        used: "399367725056"
                email: 100451397@alumnos.uc3m.es
                executable: c:\Users\Jaime\miniconda3\envs\ds-hpe-3-11\python.exe
                gpu: NVIDIA GeForce RTX 5060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 3328
                      memoryTotal: "8546942976"
                      name: NVIDIA GeForce RTX 5060 Laptop GPU
                      uuid: GPU-bf1784b3-28c2-3ce3-6d35-c13096256abd
                host: DESKTOP-9G0MLGE
                memory:
                    total: "33713815552"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\Jaime\Documents\GitHub\DS-HPE\training.ipynb
                python: CPython 3.11.14
                root: c:\Users\Jaime\Documents\GitHub\DS-HPE
                startedAt: "2025-12-15T18:35:59.616257Z"
                writerId: rvv8zu4mff2nxbcukounvl6dnrtjjrvq
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 6
                - 8
                - 53
            "2":
                - 1
                - 5
                - 6
                - 8
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.14
            "5": 0.23.0
            "8":
                - 1
                - 3
            "12": 0.23.0
            "13": windows-amd64
device:
    value: cuda
epochs:
    value: 150
lr:
    value: 0.0001
patience:
    value: 80
weight_decay:
    value: 1e-05
