wandb_version: 1

batch_size:
  value: 2048
dropout:
  value: 0.16580270210523135
epochs:
  value: 150
hidden_dims:
  value:
  - 256
  - 128
  - 64
lr:
  value: 0.00830799941238441
patience:
  value: 80
weight_decay:
  value: 1.8894630888586435e-05
