wandb_version: 1

batch_size:
  value: 512
dropout:
  value: 0.1853377966624332
epochs:
  value: 150
hidden_dims:
  value:
  - 512
  - 256
  - 128
  - 64
lr:
  value: 0.0007014100798742037
patience:
  value: 80
weight_decay:
  value: 6.712048171957736e-05
