wandb_version: 1

batch_size:
  value: 2048
dropout:
  value: 0.25222616402333775
epochs:
  value: 150
hidden_dims:
  value:
  - 256
  - 128
  - 64
lr:
  value: 0.0010712250248524988
patience:
  value: 80
weight_decay:
  value: 2.509643829606148e-05
