wandb_version: 1

batch_size:
  value: 512
dropout:
  value: 0.48074127686692814
epochs:
  value: 150
hidden_dims:
  value:
  - 384
  - 192
  - 96
lr:
  value: 0.004298805563210925
patience:
  value: 50
weight_decay:
  value: 1.0e-06
