wandb_version: 1

batch_size:
  value: 1028
dropout:
  value: 0.15559998021833732
epochs:
  value: 150
hidden_dims:
  value:
  - 512
  - 256
  - 128
lr:
  value: 0.0009719478103336032
patience:
  value: 80
weight_decay:
  value: 1.0e-05
